---
title: "Force Plate Combining and Data Cleaning into .csv"
author: "Jordyn Maurer"
date: "9/11/2025"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Preliminary Data Cleaning of Previously Worked Data w/ Force Plate
```{r}
getwd()
# updating file path
setwd("C:/Users/jordy/OneDrive/Documents/Coach_scott/mRSI_BRFD")

# loading in initial libraries
library(dplyr)
library(purrr)
library(tidyr)
library(readr) 
library(stringr)
```

### Loading in initial force plate datasets
```{r}
BB = read.csv("BB.csv")
Fencing = read.csv("Fencing.csv")
Golf = read.csv("Golf.csv")
MBB = read.csv("MBB.csv")
WBB = read.csv("WBB.csv")
WLAX = read.csv("WLAX.csv")
MLAX = read.csv("MLAX.csv")
FB = read.csv("FB_CMJ_Data.csv")
WSC = read.csv("WSC.csv")
Volleyball = read.csv("Volleyball.csv")
MSD       <- read.csv("MSD_SPRING_CMJ.csv")
WSD       <- read.csv("WSD_SPRING_CMJ.csv")
BB_Feb        <- read.csv("BB_Feb.csv")
Fencing_Feb   <- read.csv("Fencing_Feb.csv")
Golf_Feb      <- read.csv("Golf_Feb.csv")
MBB_Feb       <- read.csv("MBB_Feb.csv")
WBB_Feb       <- read.csv("WBB_Feb.csv")
WLAX_Feb      <- read.csv("WLAX_Feb.csv")
MLAX_Feb      <- read.csv("MLAX_Feb.csv")
```


```{r}
## accounting for different variable types before merging

# putting the datasets in a named list
dfs <- list(
  BB = BB, Fencing = Fencing, Golf = Golf, MBB = MBB, WBB = WBB,
  WLAX = WLAX, MLAX = MLAX, FB = FB, WSC = WSC, Volleyball = Volleyball,
  MSD = MSD, WSD = WSD, BB_Feb = BB_Feb, Fencing_Feb = Fencing_Feb,
  Golf_Feb = Golf_Feb, MBB_Feb = MBB_Feb, WBB_Feb = WBB_Feb,
  WLAX_Feb = WLAX_Feb, MLAX_Feb = MLAX_Feb
)

# creating a team name map to make team names consistent across datasets
team_map <- c(
  BB="BB", Fencing="Fencing", Golf="Golf", MBB="MBB", WBB="WBB",
  WLAX="WLAX", MLAX="MLAX", FB="FB", WSC="WSC", Volleyball="Volleyball",
  MSD="MSD", WSD="WSD",
  BB_Feb="BB", Fencing_Feb="Fencing", Golf_Feb="Golf", MBB_Feb="MBB",
  WBB_Feb="WBB", WLAX_Feb="WLAX", MLAX_Feb="MLAX"
)

# making variables consistent

to_numeric_safe <- function(x) parse_number(as.character(x))

parse_flight_time <- function(x) {
  x <- as.character(x)
  out <- suppressWarnings(as.numeric(x))
  needs_time_parse <- is.na(out) & grepl(":", x)
  if (any(needs_time_parse)) {
    split <- strsplit(x[needs_time_parse], ":", fixed = TRUE)
    secs <- vapply(split, function(v) {
      v <- suppressWarnings(as.numeric(v))
      if (length(v) == 3) v[1]*3600 + v[2]*60 + v[3]
      else if (length(v) == 2) v[1]*60 + v[2]
      else NA_real_
    }, numeric(1))
    out[needs_time_parse] <- secs
  }
  out[is.na(out)] <- parse_number(x[is.na(out)])
  out
}

# standardizing Segment column if it appears under other names + adding Team column
standardize_names_and_team <- function(df, list_name) {
  out <- df
  if ("Name..Coded." %in% names(out) && !"Segment" %in% names(out)) {
    out <- dplyr::rename(out, Segment = `Name..Coded.`)
  } else if ("Code.Name" %in% names(out) && !"Segment" %in% names(out)) {
    out <- dplyr::rename(out, Segment = `Code.Name`)
  }
  out %>% mutate(Team = team_map[[list_name]])
}

standardized <- imap(dfs, standardize_names_and_team)

col_classes <- standardized %>%
  imap(~ map_chr(.x, ~ class(.x)[1]) %>%
         tibble(col = names(.x), class = ., dataset = .y)) %>%
  list_rbind()

conflicts <- col_classes %>%
  distinct(col, class) %>%
  add_count(col, name = "n_classes") %>%
  filter(n_classes > 1) %>%
  arrange(col)

cols_to_numeric <- conflicts %>%
  group_by(col) %>%
  summarize(any_numeric = any(class %in% c("numeric","integer","double")),
            .groups="drop") %>%
  filter(any_numeric) %>%
  pull(col)

# always force Flight.Time to numeric because this variable was causing merging issues
cols_force_numeric <- union(cols_to_numeric, "Flight.Time")

standardized_harmonized <- map(standardized, \(df) {
  df <- df %>%
    mutate(across(any_of(setdiff(cols_force_numeric, "Flight.Time")), to_numeric_safe))
  if ("Flight.Time" %in% names(df)) {
    df <- df %>% mutate(Flight.Time = parse_flight_time(Flight.Time))
  }
  df
})

# combining the force plate data
all_teams_data <- bind_rows(standardized_harmonized)

glimpse(all_teams_data)
head(all_teams_data)

# checking the dimensions of the data
dim(all_teams_data)
```

```{r}
# previewing the dataset
summary(all_teams_data)
```


```{r}
# updating the Date variable as a Date not character type
all_teams_data$Date <- as.Date(all_teams_data$Date, format = "%m/%d/%Y")

# checking to see if we now have dates
summary(all_teams_data$Date)
```
From the above output, we see that our force plate data ranges from: August 2023 to March 2025. This will be important for our injury prediction.

```{r}
# renaming the dataset
force_plate_combined_data <- all_teams_data

# exporting the data as a .csv to put in GitHub
write.csv(force_plate_combined_data, 
          "force_plate_combined_data.csv", 
          row.names = FALSE)

# confirming it saved
list.files(getwd(), pattern = "csv$")
```

