---
title: "Force Plate Combining and Data Cleaning into .csv"
author: "Jordyn Maurer"
date: "9/15/2025"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Preliminary Data Cleaning of Previously Worked Data w/ Force Plate
```{r}
getwd()
# updating file path
setwd("C:/Users/jordy/OneDrive/Documents/Coach_scott/mRSI_BRFD")

# loading in initial libraries
library(dplyr)
library(purrr)
library(tidyr)
library(readr) 
library(stringr)
```



```{r}
# reading in the injury reports
aug_inj = read.csv("Injury Report August.csv")
sep_inj = read.csv("Injury Report September.csv")
oct_inj = read.csv("October Injury Report.csv")
nov_inj = read.csv("November Inj.csv")

# filtering and cleaning each dataset
## august
aug_inj <- aug_inj %>%
  select(-Teams, -ProblemReportedBy, -IncidentReportCreatedBy)

## september
sep_inj <- sep_inj %>%
  select(-Teams, -ProblemReportedBy, -IncidentReportCreatedBy) %>%
  rename(ID = X)

## october 
oct_inj <- oct_inj %>%
  select(-Teams, -ProblemReportedBy, -IncidentReportCreatedBy)

## november 
nov_inj <- nov_inj %>%
  select(-ProblemReportedBy, -IncidentReportCreatedBy) %>%
  rename(ID = Teams)
```

```{r}
# reading in january injuries
jan_inj <- read.csv("Jan_Injuries.csv")

# cleaning and selecting necessary columns
jan_inj_clean <- jan_inj %>%
  select(-Expected.Return.Date, -Actual.Return.Date, -Days.Out, -Problem.Status, -Reported.Date)

jan_inj_clean <- jan_inj_clean %>%
  rename(ID = ID.) %>%
  rename(ProblemDate = Problem.Date) %>%
  rename(InjuryType = Condition) %>%
  rename(BodyPart = Body.Part) %>%
  rename(AffectedArea = Affected.Area) %>% rename(Side = Problem.Side) %>%
  rename(BodyPartName = Problem.Sites)

jan_inj_clean$ProblemDate <- mdy_hm(jan_inj_clean$ProblemDate)
jan_inj_clean$ProblemDate <- as.Date(jan_inj_clean$ProblemDate)
str(jan_inj_clean$ProblemDate)

# filtering and cleaning the other datasets 
## august
aug_inj_clean <- aug_inj %>%

aug_inj_clean$ProblemDate <- mdy(substr(aug_inj_clean$ProblemDate, 5, 15))
str(aug_inj_clean$ProblemDate)

## september
sep_inj_clean <- sep_inj %>%

sep_inj_clean$ProblemDate <- mdy(substr(sep_inj_clean$ProblemDate, 5, 15))
str(sep_inj_clean$ProblemDate)

## october 
oct_inj_clean <- oct_inj 

oct_inj_clean$ProblemDate <- mdy(substr(oct_inj_clean$ProblemDate, 5, 15))
str(oct_inj_clean$ProblemDate)

## november 
nov_inj_clean <- nov_inj 

nov_inj_clean$ProblemDate <- mdy(substr(nov_inj_clean$ProblemDate, 5, 15))
str(nov_inj_clean$ProblemDate)

# combining with other injury data
combined_inj <- bind_rows(aug_inj_clean, sep_inj_clean, oct_inj_clean, nov_inj_clean, jan_inj_clean) %>%
  select(-IncidentReportCreatedOnDate)
head(combined_inj)
View(combined_inj)
```

