---
title: "Reproducibility_starbucks"
output: html_document
date: "2025-09-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
```



```{r}
# uploading the dataset using relative file paths (I know this will not work for all versions and is NOT very reproducible)
starbucks_locations <- read_csv("DA_401/data/starbucks_locations.csv")
View(starbucks_locations)
```

```{r}
# For the following code, I used Lab 5 (defining KNN functions) from DA 352 with Dr. Wang as a reference

# euclidean distance function 
euclidean_distance <- function(a, b){
  if (length(a) == length(b)) sqrt(sum((a - b)^2))
}

# creating the knn function with longitude and latitude as inputs and returning the store name of the nearest starbucks
knn_nearest_store_function <- function(X_train, Y_train, X_new, K, distance) {
  dist <- apply(X_train, 1, distance, X_new)
  neighbor_ind <- order(dist)[1:K]
  Y_new <- Y_train[neighbor_ind][1]
  return(Y_new)
}
```


```{r}
# applying the above function to our data 
X_train <- as.matrix(starbucks_locations %>% select(Longitude, Latitude))
Y_train <- starbucks_locations$`Store Name`

# INPUT YOUR DESIRED LONGITUDE AND LATITUDE HERE
X_new <- c(-30, 50)

# returns the nearest starbucks name based on the above longitude and latitude
nearest_store <- knn_nearest_store_function(X_train, Y_train, X_new, K = 1, distance = euclidean_distance)
nearest_store
```

